---------------------------------
ChannelOption					 |
---------------------------------
	# ChannelOption 提供的标准配置项


	ALLOCATOR
	RCVBUF_ALLOCATOR
	MESSAGE_SIZE_ESTIMATOR
	CONNECT_TIMEOUT_MILLIS
	MAX_MESSAGES_PER_READ

	WRITE_SPIN_COUNT
	WRITE_BUFFER_HIGH_WATER_MARK
	WRITE_BUFFER_LOW_WATER_MARK
	WRITE_BUFFER_WATER_MARK
	ALLOW_HALF_CLOSURE

	AUTO_READ
	AUTO_CLOSE

	SO_BROADCAST
	SO_KEEPALIVE
	SO_SNDBUF
	SO_RCVBUF
	SO_REUSEADDR
	SO_LINGER
	SO_BACKLOG
	SO_TIMEOUT

	IP_TOS
	IP_MULTICAST_ADDR
	IP_MULTICAST_IF
	IP_MULTICAST_TTL
	IP_MULTICAST_LOOP_DISABLED
	TCP_NODELAY

	DATAGRAM_CHANNEL_ACTIVE_ON_REGISTRATION
	SINGLE_EVENTEXECUTOR_PER_GROUP